# Generated by Django 5.2.7 on 2025-10-02 17:12

import django.db.models.deletion
import escola.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('responsavel', models.CharField(blank=True, max_length=120, verbose_name='Responsável')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('dt_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[escola.models.validar_cpf], verbose_name='CPF')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Turma')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária (h)')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='escola.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='escola.turma')),
            ],
            options={
                'ordering': ['turma', 'aluno'],
                'unique_together': {('aluno', 'turma')},
            },
        ),
    ]
